### ISSUE TITLE
Cosmos - Plugin - New blocksync check plugin

### ISSUE THREAD

**Issue by heejin-github** [dsrvlabs/vatz#304]
- parents : #236 
- related : #294 

TODO : Develop new blocksync check plugin for cosmoshub.

**Comment by heejin-github** [comment]
> > > @heejin-github Is this done? Can I try it?
> > 
> > 
> > @xellos00 Not yet, maybe next week we can test.
> 
> @heejin-github I am going to follow up comming vatz weekly sync but Can you confirm that two Items working properly by next week?
> 
> * New blocksync check
> * is_alive [Plugins Error `is_alived` #302](https://github.com/dsrvlabs/vatz/issues/302)

@xellos00 
Yes, I will. Initial draft of block sync plugin was uploaded.(https://github.com/dsrvlabs/vatz-plugin-cosmoshub/pull/23)
However about issue #302, 
As I checked your log in this issue, It seems that the rpc port 26657 was occupied some other process or any other reasons. so, I'm not sure it could be solved by plugin side.
Did you have similar issue on other node except `ybl-certik-mainnet-validator-do-frankfrut`?
I think this issue only happened on `ybl-certik-mainnet-validator-do-frankfrut`node so far.

```
2022-11-17T17:20:38Z INF Execute module=grpc
2022-11-17T17:20:38Z ERR Get "http://localhost:26657/health": dial tcp: lookup localhost: device or resource busy Response=Error
2022-11-17T17:20:38Z ERR Get "http://localhost:26657/health": dial tcp: lookup localhost: device or resource busy GetHealth=Error
```

**Comment by xellos00** [comment]
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/6308023/203568453-7e4ea238-bc90-4094-94ea-f40afbeb0dd4.png">

**Comment by skonhwang** [comment]
## Error Report about new block sync
![image](https://user-images.githubusercontent.com/106724973/204477464-df2649d6-87b3-402a-b290-6768ad9e6c2f.png)<br>
- It was voting end time of proposal 84
- Error log
```sh
panic: runtime error: index out of range [0] with length 0

goroutine 45 [running]:
github.com/dsrvlabs/vatz-plugin-cosmoshub/plugins/node_block_sync/policy.(*blockSyncEstimator).Estimate(0xc000073c80?, {0xc0002014c0, 0x64, 0x1?}, 0x6fc23ac00, 0x1bf08eb00)
        /root/git/vatz-plugin-cosmoshub/plugins/node_block_sync/policy/policy.go:76 +0x4f9
main.pluginFeature(0x7?, 0x96ba41?)
        /root/git/vatz-plugin-cosmoshub/plugins/node_block_sync/main.go:69 +0x13b
github.com/dsrvlabs/vatz/sdk.(*grpcServer).Execute(0xc000070d00, {0xc0000a4e80?, 0x5e0ee6?}, 0xc0000a4e80)
        /root/go/pkg/mod/github.com/dsrvlabs/vatz/sdk@v0.0.0-20221011062114-75a42d7cf117/grpc.go:52 +0x184
github.com/dsrvlabs/vatz-proto/plugin/v1._Plugin_Execute_Handler({0x907b20?, 0xc000070d00}, {0xa37ce0, 0xc0000a19e0}, 0xc0002e8000, 0x0)
        /root/go/pkg/mod/github.com/dsrvlabs/vatz-proto@v0.0.0-20220908182122-4c28400b195f/plugin/v1/plugin_grpc.pb.go:112 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000240000, {0xa39c18, 0xc000203040}, 0xc0000d6000, 0xc000218270, 0xd463d8, 0x0)
        /root/go/pkg/mod/google.golang.org/grpc@v1.49.0/server.go:1301 +0xb0b
google.golang.org/grpc.(*Server).handleStream(0xc000240000, {0xa39c18, 0xc000203040}, 0xc0000d6000, 0x0)
        /root/go/pkg/mod/google.golang.org/grpc@v1.49.0/server.go:1642 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /root/go/pkg/mod/google.golang.org/grpc@v1.49.0/server.go:938 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /root/go/pkg/mod/google.golang.org/grpc@v1.49.0/server.go:936 +0x28a
```
- Code
```go
 70     // calculate block time.
 71     if len(history) == 0 {
 72         log.Info().Str("policy", "blockSyncEstimator").Msg("not enough samples")
 73         return AlertStatusUnknown, nil
 74     }
 75
 76     firstStatus := statusInRange[0]
 77     lastStatus := statusInRange[len(statusInRange)-1]
 78
 79     timeRange := lastStatus.TimeCreated.Sub(firstStatus.TimeCreated)
 80     blockInc := lastStatus.BlockHeight - firstStatus.BlockHeight
```

**Comment by heejin-github** [comment]
closed by https://github.com/dsrvlabs/vatz-plugin-cosmoshub/pull/23
