### ISSUE TITLE
Missed Options params in healthMsg

### ISSUE THREAD

**Issue by heejin-github** [dsrvlabs/vatz#360]
### Checklist
- [x] Bug from Service (Vatz)
- [ ] Bug from Plugin (Vatz) 
- [ ] Malfunction on CI/CD 
- [ ] etc(e.g, Hardware version doesn't match, )

---

### **Describe the bug**
> A clear and concise description of what the bug is.
panic happened when healthcheck.

### **How to Reproduce**
> Steps to reproduce the behavior:

1. set pagerduty in vatz config yaml
2. send notification when the healthcheck time.

### **Expected behavior**
> A clear and concise description of what you expected to happen.
do not panic

### **Screenshots**
> If applicable, add screenshots to help explain your problem.
```
panic: interface conversion: interface {} is nil, not string

goroutine 211 [running]:
github.com/dsrvlabs/vatz/manager/dispatcher.(*pagerduty).SendNotification(0xc000082f00, {{0xcb0908, 0xf}, 0x3, {0xcb08f9, 0xf}, 0x4, {0xca7deb, 0x4}, 0x0})
        /root/git/vatz/manager/dispatcher/pagerduty.go:41 +0xba5
github.com/dsrvlabs/vatz/manager/healthcheck.(*healthChecker).VATZHealthCheck.func1()
        /root/git/vatz/manager/healthcheck/general_healthcheck.go:87 +0xf4
github.com/robfig/cron/v3.FuncJob.Run(0xc0000577d0?)
        /usr/local/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:136 +0x1a
github.com/robfig/cron/v3.(*Cron).startJob.func1()
        /usr/local/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:312 +0x6a
created by github.com/robfig/cron/v3.(*Cron).startJob
        /usr/local/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:310 +0xad

```

**Comment by heejin-github** [comment]
issue reported from #351 
- https://github.com/dsrvlabs/vatz/issues/351#issuecomment-1369586760
